apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: lab1
spec:
  selector:
    app: jaeger
  ports:
  - port: 16686
    targetPort: 16686
    name: http-query
  - port: 14250
    targetPort: 14250
    name: grpc
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: lab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.47
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        ports:
        - containerPort: 16686
        - containerPort: 14250
        - containerPort: 4317
        - containerPort: 4318
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 