apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-api-config
  namespace: lab1
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "Otlp": {
        "Endpoint": "http://otel-collector:4317",
        "ServiceName": "orders-api",
        "ServiceVersion": "1.0.0"
      },
      "Chaos": {
        "ErrorRate": 0.002,
        "SlowRequestRate": 0.05,
        "SlowRequestDelayMs": 500
      }
    } 